// AUTO-GENERATED BY C++ OVERSEER (V3-ROBUST)
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>
#include <pybind11/operators.h>
#include "../src_cpp/Helloworld.cpp"

namespace py = pybind11;

PYBIND11_MODULE(helloworld, m) {
    py::class_<HelloWorld>(m, "HelloWorld")
        .def(py::init<>())
        .def("greet", &HelloWorld::greet)
    ;
}
