// AUTO-GENERATED BY C++ OVERSEER (V3-ROBUST)
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>
#include <pybind11/operators.h>
#include "../src_cpp/IntegrationTest.cpp"

namespace py = pybind11;

PYBIND11_MODULE(integration_test, m) {
    py::class_<BaseSystem>(m, "BaseSystem")
        .def(py::init<int>())
        .def("reset", &BaseSystem::reset)
    ;
    py::class_<ComputeNode, BaseSystem>(m, "ComputeNode")
        .def(py::init<>())
        .def(py::init<const std::vector<float>&>())
        .def("process", py::overload_cast<float>(&ComputeNode::process))
        .def("process", py::overload_cast<float, int>(&ComputeNode::process))
        .def("__add__", &ComputeNode::operator+)
        .def("get_average", &ComputeNode::get_average)
        .def("version", &ComputeNode::version)
    ;
}
